# Test FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/faces/?image_url=https%3A%2F%2Fwww.ppic.org%2Fwp-content%2Fuploads%2FCrowd-of-Diverse-People_800x528-768x512.jpg
Accept: application/json

###

POST http://127.0.0.1:8000/enhance/?image_url=https%3A%2F%2Fwww.ppic.org%2Fwp-content%2Fuploads%2FCrowd-of-Diverse-People_800x528-768x512.jpg
Accept: application/json
Content-Type: application/json

{
  "x1": 285,
  "x2": 426,
  "y1": 373,
  "y2": 514
}

###