# Test FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/faces/?image_url=https%3A%2F%2Fwww.ppic.org%2Fwp-content%2Fuploads%2FCrowd-of-Diverse-People_800x528-768x512.jpg
Accept: application/json

###

POST http://127.0.0.1:8000/enhance/?image_url=https%3A%2F%2Fwww.ppic.org%2Fwp-content%2Fuploads%2FCrowd-of-Diverse-People_800x528-768x512.jpg
Accept: application/json
Content-Type: application/json

{
  "x1": 285,
  "x2": 426,
  "y1": 373,
  "y2": 514
}

###
POST http://127.0.0.1:8000/enhance/?image_url=https%3A%2F%2Fwww.ppic.org%2Fwp-content%2Fuploads%2FCrowd-of-Diverse-People_800x528-768x512.jpg
Accept: application/json
Content-Type: application/json

{
  "x1": 476,
  "x2": 551,
  "y1": 334,
  "y2": 433
}

###

POST http://127.0.0.1:8000/frontalize/?image_url=https%3A%2F%2Fgithub.com%2FHRLTY%2FTP-GAN%2Fblob%2Fmaster%2Fdata-example%2F001_01_01_200_08_cropped.png%3Fraw%3Dtrue
Accept: application/json

###

POST http://127.0.0.1:8000/frontalize/?image_url=https%3A%2F%2Fgithub.com%2FHRLTY%2FTP-GAN%2Fblob%2Fmaster%2Fdata-example%2F001_01_01_041_07_cropped.png%3Fraw%3Dtrue
Accept: application/json

###

POST http://127.0.0.1:8000/frontalize/?image_url=https%3A%2F%2Fgithub.com%2FHRLTY%2FTP-GAN%2Fblob%2Fmaster%2Fdata-example%2F001_01_01_050_06_cropped.png%3Fraw%3Dtrue
Accept: application/json

###

POST http://127.0.0.1:8000/frontalize/?image_url=https%3A%2F%2Fgithub.com%2FHRLTY%2FTP-GAN%2Fblob%2Fmaster%2Fdata-example%2F001_01_01_140_06_cropped.png%3Fraw%3Dtrue
Accept: application/json
