FROM python:3.11.4-slim-bullseye as base

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
    git \
    libopenblas0 \
    libtcmalloc-minimal4 \
    build-essential \
    libgl1 \
    libglib2.0-0 \
 && rm -rf /var/lib/apt/lists/*

COPY app /app

WORKDIR /app

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && \
      pip install --no-cache-dir git+https://github.com/facebookresearch/pytorch3d.git@297020a4b1d7492190cb4a909cafbd2c81a12cb5

RUN python ./common/asset_downloader.py

## development image.
#FROM base as development
#
#COPY requirements_dev.txt requirements_dev.txt
#
#RUN pip install -r requirements_dev.txt
#
#
## testing image.
#FROM base as testing
#
#RUN pip install pytest && pip install requests
#
#
# production image.
FROM base as production

ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4

ARG PORT=8080
ARG HOST=0.0.0.0
ARG APP_MODULE=main:app
ARG WEB_CONCURRENCY=1

ENV MODE=production
ENV APP_MODULE=${APP_MODULE}
#ENV WEB_CONCURRENCY=${WEB_CONCURRENCY}}
ENV HOST=${HOST}
ENV PORT=${PORT}

STOPSIGNAL SIGTERM
EXPOSE ${PORT}

ENTRYPOINT uvicorn ${APP_MODULE} --proxy-headers --port ${PORT} --host ${HOST}
